// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave.DotLiquid")>]
[<assembly: AssemblyProductAttribute("Suave.DotLiquid")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © (c) Ademar Gonzalez, Henrik Feldt, contributors 2018")>]
[<assembly: AssemblyDescriptionAttribute("Suave is a simple web development F# library providing a lightweight web server and a set of combinators to manipulate route flow and task composition.")>]
[<assembly: AssemblyVersionAttribute("3.0.0")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave.DotLiquid"
    let [<Literal>] AssemblyProduct = "Suave.DotLiquid"
    let [<Literal>] AssemblyCopyright = "Copyright © (c) Ademar Gonzalez, Henrik Feldt, contributors 2018"
    let [<Literal>] AssemblyDescription = "Suave is a simple web development F# library providing a lightweight web server and a set of combinators to manipulate route flow and task composition."
    let [<Literal>] AssemblyVersion = "3.0.0"
    let [<Literal>] AssemblyFileVersion = "3.0.0"
